### ISSUE TITLE
Great Scrip but... I just used it on Ubuntu 24.04 

### ISSUE THREAD

**Issue by rmeadejr** [keepittechie/mcsli#3]
As a Minecraft script Java 17 should be updated to 21.  I was able to get Minecraft working but something is not right.  The script doesn't run MC and edit the EULA and I think it is failing so the service doesn't get created.  Apache gets installed but the website doesn't work right.

Also, you have ipddress/5000 I think that should be ipaddress:5000

**Comment by realSZ27** [comment]
Just made #4, which will hopefully fix your issues.

Also, mind putting your full output when you run the script?

**Comment by rmeadejr** [comment]
Thanks for getting back to me.  I ran the script again on a fresh install.
Still not running Minecraft.  Here is the output:


***@***.***:~$ sudo bash ./install_full.sh
[sudo] password for minecraftuser:
info: Selecting UID from range 100 to 999 ...

info: Selecting GID from range 100 to 999 ...
info: Adding system user `minecraft' (UID 105) ...
info: Adding new group `minecraft' (GID 104) ...
info: Adding new user `minecraft' (UID 105) with group `minecraft' ...
info: Not creating `/nonexistent'.
Hit:1 http://us.archive.ubuntu.com/ubuntu noble InRelease
Hit:2 http://security.ubuntu.com/ubuntu noble-security InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu noble-backports InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
11 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
wget is already the newest version (1.21.4-1ubuntu4.1).
wget set to manually installed.
The following additional packages will be installed:
  alsa-topology-conf alsa-ucm-conf ca-certificates-java java-common
libasound2-data libasound2t64 libavahi-client3
  libavahi-common-data libavahi-common3 libcups2t64 libgraphite2-3
libharfbuzz0b liblcms2-2 libnspr4 libnss3
  libpcsclite1
Suggested packages:
  default-jre alsa-utils libasound2-plugins cups-common liblcms2-utils
pcscd libnss-mdns fonts-dejavu-extra
  fonts-ipafont-gothic fonts-ipafont-mincho fonts-wqy-microhei |
fonts-wqy-zenhei fonts-indic
The following NEW packages will be installed:
  alsa-topology-conf alsa-ucm-conf ca-certificates-java java-common
libasound2-data libasound2t64 libavahi-client3
  libavahi-common-data libavahi-common3 libcups2t64 libgraphite2-3
libharfbuzz0b liblcms2-2 libnspr4 libnss3
  libpcsclite1 openjdk-17-jre-headless
0 upgraded, 17 newly installed, 0 to remove and 11 not upgraded.
Need to get 51.0 MB of archives.
After this operation, 202 MB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu noble/main amd64
alsa-topology-conf all 1.2.5.1-2 [15.5 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu noble/main amd64 libasound2-data
all 1.2.11-1build2 [21.0 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu noble/main amd64 libasound2t64
amd64 1.2.11-1build2 [399 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu noble/main amd64 alsa-ucm-conf
all 1.2.10-1ubuntu5 [63.1 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu noble/main amd64
ca-certificates-java all 20240118 [11.6 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu noble/main amd64 java-common all
0.75+exp1 [6798 B]
Get:7 http://us.archive.ubuntu.com/ubuntu noble/main amd64
libavahi-common-data amd64 0.8-13ubuntu6 [29.7 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu noble/main amd64 libavahi-common3
amd64 0.8-13ubuntu6 [23.3 kB]
Get:9 http://us.archive.ubuntu.com/ubuntu noble/main amd64 libavahi-client3
amd64 0.8-13ubuntu6 [26.8 kB]
Get:10 http://us.archive.ubuntu.com/ubuntu noble-updates/main amd64
libcups2t64 amd64 2.4.7-1.2ubuntu7.2 [272 kB]
Get:11 http://us.archive.ubuntu.com/ubuntu noble/main amd64 libgraphite2-3
amd64 1.3.14-2build1 [73.0 kB]
Get:12 http://us.archive.ubuntu.com/ubuntu noble/main amd64 libharfbuzz0b
amd64 8.3.0-2build2 [469 kB]
Get:13 http://us.archive.ubuntu.com/ubuntu noble/main amd64 liblcms2-2
amd64 2.14-2build1 [161 kB]
Get:14 http://us.archive.ubuntu.com/ubuntu noble/main amd64 libnspr4 amd64
2:4.35-1.1build1 [117 kB]
Get:15 http://us.archive.ubuntu.com/ubuntu noble/main amd64 libnss3 amd64
2:3.98-1build1 [1445 kB]
Get:16 http://us.archive.ubuntu.com/ubuntu noble/main amd64 libpcsclite1
amd64 2.0.3-1build1 [21.4 kB]
Get:17 http://us.archive.ubuntu.com/ubuntu noble/main amd64
openjdk-17-jre-headless amd64 17.0.11+9-1 [47.9 MB]
Fetched 51.0 MB in 3s (14.9 MB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package alsa-topology-conf.
(Reading database ... 72376 files and directories currently installed.)
Preparing to unpack .../00-alsa-topology-conf_1.2.5.1-2_all.deb ...
Unpacking alsa-topology-conf (1.2.5.1-2) ...
Selecting previously unselected package libasound2-data.
Preparing to unpack .../01-libasound2-data_1.2.11-1build2_all.deb ...
Unpacking libasound2-data (1.2.11-1build2) ...
Selecting previously unselected package libasound2t64:amd64.
Preparing to unpack .../02-libasound2t64_1.2.11-1build2_amd64.deb ...
Unpacking libasound2t64:amd64 (1.2.11-1build2) ...
Selecting previously unselected package alsa-ucm-conf.
Preparing to unpack .../03-alsa-ucm-conf_1.2.10-1ubuntu5_all.deb ...
Unpacking alsa-ucm-conf (1.2.10-1ubuntu5) ...
Selecting previously unselected package ca-certificates-java.
Preparing to unpack .../04-ca-certificates-java_20240118_all.deb ...
Unpacking ca-certificates-java (20240118) ...
Selecting previously unselected package java-common.
Preparing to unpack .../05-java-common_0.75+exp1_all.deb ...
Unpacking java-common (0.75+exp1) ...
Selecting previously unselected package libavahi-common-data:amd64.
Preparing to unpack .../06-libavahi-common-data_0.8-13ubuntu6_amd64.deb ...
Unpacking libavahi-common-data:amd64 (0.8-13ubuntu6) ...
Selecting previously unselected package libavahi-common3:amd64.
Preparing to unpack .../07-libavahi-common3_0.8-13ubuntu6_amd64.deb ...
Unpacking libavahi-common3:amd64 (0.8-13ubuntu6) ...
Selecting previously unselected package libavahi-client3:amd64.
Preparing to unpack .../08-libavahi-client3_0.8-13ubuntu6_amd64.deb ...
Unpacking libavahi-client3:amd64 (0.8-13ubuntu6) ...
Selecting previously unselected package libcups2t64:amd64.
Preparing to unpack .../09-libcups2t64_2.4.7-1.2ubuntu7.2_amd64.deb ...
Unpacking libcups2t64:amd64 (2.4.7-1.2ubuntu7.2) ...
Selecting previously unselected package libgraphite2-3:amd64.
Preparing to unpack .../10-libgraphite2-3_1.3.14-2build1_amd64.deb ...
Unpacking libgraphite2-3:amd64 (1.3.14-2build1) ...
Selecting previously unselected package libharfbuzz0b:amd64.
Preparing to unpack .../11-libharfbuzz0b_8.3.0-2build2_amd64.deb ...
Unpacking libharfbuzz0b:amd64 (8.3.0-2build2) ...
Selecting previously unselected package liblcms2-2:amd64.
Preparing to unpack .../12-liblcms2-2_2.14-2build1_amd64.deb ...
Unpacking liblcms2-2:amd64 (2.14-2build1) ...
Selecting previously unselected package libnspr4:amd64.
Preparing to unpack .../13-libnspr4_2%3a4.35-1.1build1_amd64.deb ...
Unpacking libnspr4:amd64 (2:4.35-1.1build1) ...
Selecting previously unselected package libnss3:amd64.
Preparing to unpack .../14-libnss3_2%3a3.98-1build1_amd64.deb ...
Unpacking libnss3:amd64 (2:3.98-1build1) ...
Selecting previously unselected package libpcsclite1:amd64.
Preparing to unpack .../15-libpcsclite1_2.0.3-1build1_amd64.deb ...
Unpacking libpcsclite1:amd64 (2.0.3-1build1) ...
Selecting previously unselected package openjdk-17-jre-headless:amd64.
Preparing to unpack .../16-openjdk-17-jre-headless_17.0.11+9-1_amd64.deb ...
Unpacking openjdk-17-jre-headless:amd64 (17.0.11+9-1) ...
Setting up libgraphite2-3:amd64 (1.3.14-2build1) ...
Setting up liblcms2-2:amd64 (2.14-2build1) ...
Setting up java-common (0.75+exp1) ...
Setting up libasound2-data (1.2.11-1build2) ...
Setting up libasound2t64:amd64 (1.2.11-1build2) ...
Setting up libnspr4:amd64 (2:4.35-1.1build1) ...
Setting up libavahi-common-data:amd64 (0.8-13ubuntu6) ...
Setting up libpcsclite1:amd64 (2.0.3-1build1) ...
Setting up alsa-topology-conf (1.2.5.1-2) ...
Setting up libharfbuzz0b:amd64 (8.3.0-2build2) ...
Setting up ca-certificates-java (20240118) ...
No JRE found. Skipping Java certificates setup.
Setting up alsa-ucm-conf (1.2.10-1ubuntu5) ...
Setting up libavahi-common3:amd64 (0.8-13ubuntu6) ...
Setting up libnss3:amd64 (2:3.98-1build1) ...
Setting up openjdk-17-jre-headless:amd64 (17.0.11+9-1) ...
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/java to
provide /usr/bin/java (java) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/jpackage
to provide /usr/bin/jpackage (jpackage) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/bin/keytool
to provide /usr/bin/keytool (keytool) in auto mode
update-alternatives: using
/usr/lib/jvm/java-17-openjdk-amd64/bin/rmiregistry to provide
/usr/bin/rmiregistry (rmiregistry) in auto mode
update-alternatives: using /usr/lib/jvm/java-17-openjdk-amd64/lib/jexec to
provide /usr/bin/jexec (jexec) in auto mode
Setting up libavahi-client3:amd64 (0.8-13ubuntu6) ...
Setting up libcups2t64:amd64 (2.4.7-1.2ubuntu7.2) ...
Processing triggers for libc-bin (2.39-0ubuntu8.2) ...
Processing triggers for ca-certificates-java (20240118) ...
Adding debian:ACCVRAIZ1.pem
Adding debian:AC_RAIZ_FNMT-RCM.pem
Adding debian:AC_RAIZ_FNMT-RCM_SERVIDORES_SEGUROS.pem
Adding debian:ANF_Secure_Server_Root_CA.pem
Adding debian:Actalis_Authentication_Root_CA.pem
Adding debian:AffirmTrust_Commercial.pem
Adding debian:AffirmTrust_Networking.pem
Adding debian:AffirmTrust_Premium.pem
Adding debian:AffirmTrust_Premium_ECC.pem
Adding debian:Amazon_Root_CA_1.pem
Adding debian:Amazon_Root_CA_2.pem
Adding debian:Amazon_Root_CA_3.pem
Adding debian:Amazon_Root_CA_4.pem
Adding debian:Atos_TrustedRoot_2011.pem
Adding debian:Atos_TrustedRoot_Root_CA_ECC_TLS_2021.pem
Adding debian:Atos_TrustedRoot_Root_CA_RSA_TLS_2021.pem
Adding debian:Autoridad_de_Certificacion_Firmaprofesional_CIF_A62634068.pem
Adding debian:BJCA_Global_Root_CA1.pem
Adding debian:BJCA_Global_Root_CA2.pem
Adding debian:Baltimore_CyberTrust_Root.pem
Adding debian:Buypass_Class_2_Root_CA.pem
Adding debian:Buypass_Class_3_Root_CA.pem
Adding debian:CA_Disig_Root_R2.pem
Adding debian:CFCA_EV_ROOT.pem
Adding debian:COMODO_Certification_Authority.pem
Adding debian:COMODO_ECC_Certification_Authority.pem
Adding debian:COMODO_RSA_Certification_Authority.pem
Adding debian:Certainly_Root_E1.pem
Adding debian:Certainly_Root_R1.pem
Adding debian:Certigna.pem
Adding debian:Certigna_Root_CA.pem
Adding debian:Certum_EC-384_CA.pem
Adding debian:Certum_Trusted_Network_CA.pem
Adding debian:Certum_Trusted_Network_CA_2.pem
Adding debian:Certum_Trusted_Root_CA.pem
Adding debian:CommScope_Public_Trust_ECC_Root-01.pem
Adding debian:CommScope_Public_Trust_ECC_Root-02.pem
Adding debian:CommScope_Public_Trust_RSA_Root-01.pem
Adding debian:CommScope_Public_Trust_RSA_Root-02.pem
Adding debian:Comodo_AAA_Services_root.pem
Adding debian:D-TRUST_BR_Root_CA_1_2020.pem
Adding debian:D-TRUST_EV_Root_CA_1_2020.pem
Adding debian:D-TRUST_Root_Class_3_CA_2_2009.pem
Adding debian:D-TRUST_Root_Class_3_CA_2_EV_2009.pem
Adding debian:DigiCert_Assured_ID_Root_CA.pem
Adding debian:DigiCert_Assured_ID_Root_G2.pem
Adding debian:DigiCert_Assured_ID_Root_G3.pem
Adding debian:DigiCert_Global_Root_CA.pem
Adding debian:DigiCert_Global_Root_G2.pem
Adding debian:DigiCert_Global_Root_G3.pem
Adding debian:DigiCert_High_Assurance_EV_Root_CA.pem
Adding debian:DigiCert_TLS_ECC_P384_Root_G5.pem
Adding debian:DigiCert_TLS_RSA4096_Root_G5.pem
Adding debian:DigiCert_Trusted_Root_G4.pem
Adding debian:Entrust.net_Premium_2048_Secure_Server_CA.pem
Adding debian:Entrust_Root_Certification_Authority.pem
Adding debian:Entrust_Root_Certification_Authority_-_EC1.pem
Adding debian:Entrust_Root_Certification_Authority_-_G2.pem
Adding debian:Entrust_Root_Certification_Authority_-_G4.pem
Adding debian:GDCA_TrustAUTH_R5_ROOT.pem
Adding debian:GLOBALTRUST_2020.pem
Adding debian:GTS_Root_R1.pem
Adding debian:GTS_Root_R2.pem
Adding debian:GTS_Root_R3.pem
Adding debian:GTS_Root_R4.pem
Adding debian:GlobalSign_ECC_Root_CA_-_R4.pem
Adding debian:GlobalSign_ECC_Root_CA_-_R5.pem
Adding debian:GlobalSign_Root_CA.pem
Adding debian:GlobalSign_Root_CA_-_R3.pem
Adding debian:GlobalSign_Root_CA_-_R6.pem
Adding debian:GlobalSign_Root_E46.pem
Adding debian:GlobalSign_Root_R46.pem
Adding debian:Go_Daddy_Class_2_CA.pem
Adding debian:Go_Daddy_Root_Certificate_Authority_-_G2.pem
Adding debian:HARICA_TLS_ECC_Root_CA_2021.pem
Adding debian:HARICA_TLS_RSA_Root_CA_2021.pem
Adding
debian:Hellenic_Academic_and_Research_Institutions_ECC_RootCA_2015.pem
Adding debian:Hellenic_Academic_and_Research_Institutions_RootCA_2015.pem
Adding debian:HiPKI_Root_CA_-_G1.pem
Adding debian:Hongkong_Post_Root_CA_3.pem
Adding debian:ISRG_Root_X1.pem
Adding debian:ISRG_Root_X2.pem
Adding debian:IdenTrust_Commercial_Root_CA_1.pem
Adding debian:IdenTrust_Public_Sector_Root_CA_1.pem
Adding debian:Izenpe.com.pem
Adding debian:Microsec_e-Szigno_Root_CA_2009.pem
Adding debian:Microsoft_ECC_Root_Certificate_Authority_2017.pem
Adding debian:Microsoft_RSA_Root_Certificate_Authority_2017.pem
Adding debian:NAVER_Global_Root_Certification_Authority.pem
Adding debian:NetLock_Arany_=Class_Gold=_Főtanúsítvány.pem
Adding debian:OISTE_WISeKey_Global_Root_GB_CA.pem
Adding debian:OISTE_WISeKey_Global_Root_GC_CA.pem
Adding debian:QuoVadis_Root_CA_1_G3.pem
Adding debian:QuoVadis_Root_CA_2.pem
Adding debian:QuoVadis_Root_CA_2_G3.pem
Adding debian:QuoVadis_Root_CA_3.pem
Adding debian:QuoVadis_Root_CA_3_G3.pem
Adding debian:SSL.com_EV_Root_Certification_Authority_ECC.pem
Adding debian:SSL.com_EV_Root_Certification_Authority_RSA_R2.pem
Adding debian:SSL.com_Root_Certification_Authority_ECC.pem
Adding debian:SSL.com_Root_Certification_Authority_RSA.pem
Adding debian:SSL.com_TLS_ECC_Root_CA_2022.pem
Adding debian:SSL.com_TLS_RSA_Root_CA_2022.pem
Adding debian:SZAFIR_ROOT_CA2.pem
Adding debian:Sectigo_Public_Server_Authentication_Root_E46.pem
Adding debian:Sectigo_Public_Server_Authentication_Root_R46.pem
Adding debian:SecureSign_RootCA11.pem
Adding debian:SecureTrust_CA.pem
Adding debian:Secure_Global_CA.pem
Adding debian:Security_Communication_ECC_RootCA1.pem
Adding debian:Security_Communication_RootCA2.pem
Adding debian:Security_Communication_RootCA3.pem
Adding debian:Security_Communication_Root_CA.pem
Adding debian:Starfield_Class_2_CA.pem
Adding debian:Starfield_Root_Certificate_Authority_-_G2.pem
Adding debian:Starfield_Services_Root_Certificate_Authority_-_G2.pem
Adding debian:SwissSign_Gold_CA_-_G2.pem
Adding debian:SwissSign_Silver_CA_-_G2.pem
Adding debian:T-TeleSec_GlobalRoot_Class_2.pem
Adding debian:T-TeleSec_GlobalRoot_Class_3.pem
Adding debian:TUBITAK_Kamu_SM_SSL_Kok_Sertifikasi_-_Surum_1.pem
Adding debian:TWCA_Global_Root_CA.pem
Adding debian:TWCA_Root_Certification_Authority.pem
Adding debian:TeliaSonera_Root_CA_v1.pem
Adding debian:Telia_Root_CA_v2.pem
Adding debian:TrustAsia_Global_Root_CA_G3.pem
Adding debian:TrustAsia_Global_Root_CA_G4.pem
Adding debian:Trustwave_Global_Certification_Authority.pem
Adding debian:Trustwave_Global_ECC_P256_Certification_Authority.pem
Adding debian:Trustwave_Global_ECC_P384_Certification_Authority.pem
Adding debian:TunTrust_Root_CA.pem
Adding debian:UCA_Extended_Validation_Root.pem
Adding debian:UCA_Global_G2_Root.pem
Adding debian:USERTrust_ECC_Certification_Authority.pem
Adding debian:USERTrust_RSA_Certification_Authority.pem
Adding debian:XRamp_Global_CA_Root.pem
Adding debian:certSIGN_ROOT_CA.pem
Adding debian:certSIGN_Root_CA_G2.pem
Adding debian:e-Szigno_Root_CA_2017.pem
Adding debian:ePKI_Root_Certification_Authority.pem
Adding debian:emSign_ECC_Root_CA_-_C3.pem
Adding debian:emSign_ECC_Root_CA_-_G3.pem
Adding debian:emSign_Root_CA_-_C1.pem
Adding debian:emSign_Root_CA_-_G1.pem
Adding debian:vTrus_ECC_Root_CA.pem
Adding debian:vTrus_Root_CA.pem
done.
Scanning processes...
Scanning candidates...
Scanning linux images...

Running kernel seems to be up-to-date.

Restarting services...

Service restarts being deferred:
 /etc/needrestart/restart.d/dbus.service
 systemctl restart systemd-logind.service

No containers need to be restarted.

User sessions running outdated binaries:
 minecraftuser @ session #1: login[1049]
 minecraftuser @ user manager service: systemd[1097]

No VM guests are running outdated hypervisor (qemu) binaries on this host.
Ubuntu system detected. Configuring UFW...
sudo: ufw: command not found
sudo: ufw: command not found
Enabling firewall...
sudo: ufw: command not found
1) paper: Very widely used (Will automatically install curl and jq if not
installed already)
2) purpur: Fork of paper; adds greater customization and some performance
gains
3) vanilla: Completely vanilla server from Mojang (Will automatically
install curl and jq if not installed already)
Choose your server software (1 for paper, 2 for purpur, 3 for vanilla): 3
What version of Minecraft would you like to use? (e.g., 1.20.4): 1.21.0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
curl is already the newest version (8.5.0-2ubuntu10.1).
curl set to manually installed.
The following additional packages will be installed:
  libjq1 libonig5
The following NEW packages will be installed:
  jq libjq1 libonig5
0 upgraded, 3 newly installed, 0 to remove and 11 not upgraded.
Need to get 378 kB of archives.
After this operation, 1125 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu noble/main amd64 libonig5 amd64
6.9.9-1build1 [172 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu noble/main amd64 libjq1 amd64
1.7.1-3build1 [141 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu noble/main amd64 jq amd64
1.7.1-3build1 [65.5 kB]
Fetched 378 kB in 0s (1208 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libonig5:amd64.
(Reading database ... 73537 files and directories currently installed.)
Preparing to unpack .../libonig5_6.9.9-1build1_amd64.deb ...
Unpacking libonig5:amd64 (6.9.9-1build1) ...
Selecting previously unselected package libjq1:amd64.
Preparing to unpack .../libjq1_1.7.1-3build1_amd64.deb ...
Unpacking libjq1:amd64 (1.7.1-3build1) ...
Selecting previously unselected package jq.
Preparing to unpack .../jq_1.7.1-3build1_amd64.deb ...
Unpacking jq (1.7.1-3build1) ...
Setting up libonig5:amd64 (6.9.9-1build1) ...
Setting up libjq1:amd64 (1.7.1-3build1) ...
Setting up jq (1.7.1-3build1) ...
Processing triggers for libc-bin (2.39-0ubuntu8.2) ...
Scanning processes...
Scanning candidates...
Scanning linux images...

Running kernel seems to be up-to-date.

Restarting services...

Service restarts being deferred:
 /etc/needrestart/restart.d/dbus.service
 systemctl restart systemd-logind.service

No containers need to be restarted.

User sessions running outdated binaries:
 minecraftuser @ session #1: login[1049]
 minecraftuser @ user manager service: systemd[1097]

No VM guests are running outdated hypervisor (qemu) binaries on this host.
curl: (2) no URL specified
curl: try 'curl --help' or 'curl --manual' for more information
http://: Invalid host name.
Minecraft Server Type: vanilla
Minecraft Server Version: 1.21.0
Changing ownership to minecraft...
Changing permissions...
Starting Minecraft server to generate eula.txt and server.properties...
Error: Unable to access jarfile /opt/minecraft/vanilla-1.21.0.jar
Accepting EULA...
sed: can't read eula.txt: No such file or directory
Creating Minecraft service...
[Unit]
Description=Minecraft Server
After=network.target
[Service]
WorkingDirectory=/opt/minecraft
User=minecraft
Nice=5
ExecStart=/usr/bin/java -Xms1024M -Xmx4G -jar
/opt/minecraft/vanilla-1.21.0.jar nogui
Restart=on-failure
[Install]
WantedBy=multi-user.target
Enabling Minecraft service...
Created symlink
/etc/systemd/system/multi-user.target.wants/minecraft.service →
/etc/systemd/system/minecraft.service.

Installing mcsli_webui...
Hit:1 http://us.archive.ubuntu.com/ubuntu noble InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu noble-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu noble-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
11 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  apache2-bin apache2-data apache2-utils libapr1t64 libaprutil1-dbd-sqlite3
libaprutil1-ldap libaprutil1t64
  libjansson4 liblua5.4-0 ssl-cert
Suggested packages:
  apache2-doc apache2-suexec-pristine | apache2-suexec-custom www-browser
ufw
The following NEW packages will be installed:
  apache2 apache2-bin apache2-data apache2-utils libapache2-mod-wsgi-py3
libapr1t64 libaprutil1-dbd-sqlite3
  libaprutil1-ldap libaprutil1t64 libjansson4 liblua5.4-0 ssl-cert
0 upgraded, 12 newly installed, 0 to remove and 11 not upgraded.
Need to get 2218 kB of archives.
After this operation, 8491 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu noble/main amd64 libapr1t64 amd64
1.7.2-3.1build2 [107 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu noble/main amd64 libaprutil1t64
amd64 1.6.3-1.1ubuntu7 [91.9 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu noble/main amd64
libaprutil1-dbd-sqlite3 amd64 1.6.3-1.1ubuntu7 [11.2 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu noble/main amd64 libaprutil1-ldap
amd64 1.6.3-1.1ubuntu7 [9116 B]
Get:5 http://us.archive.ubuntu.com/ubuntu noble/main amd64 libjansson4
amd64 2.14-2build2 [32.8 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu noble/main amd64 liblua5.4-0
amd64 5.4.6-3build2 [166 kB]
Get:7 http://us.archive.ubuntu.com/ubuntu noble-updates/main amd64
apache2-bin amd64 2.4.58-1ubuntu8.3 [1329 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu noble-updates/main amd64
apache2-data all 2.4.58-1ubuntu8.3 [163 kB]
Get:9 http://us.archive.ubuntu.com/ubuntu noble-updates/main amd64
apache2-utils amd64 2.4.58-1ubuntu8.3 [97.0 kB]
Get:10 http://us.archive.ubuntu.com/ubuntu noble-updates/main amd64 apache2
amd64 2.4.58-1ubuntu8.3 [90.2 kB]
Get:11 http://us.archive.ubuntu.com/ubuntu noble/main amd64
libapache2-mod-wsgi-py3 amd64 5.0.0-1build2 [103 kB]
Get:12 http://us.archive.ubuntu.com/ubuntu noble/main amd64 ssl-cert all
1.1.2ubuntu1 [17.8 kB]
Fetched 2218 kB in 0s (5411 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libapr1t64:amd64.
(Reading database ... 73555 files and directories currently installed.)
Preparing to unpack .../00-libapr1t64_1.7.2-3.1build2_amd64.deb ...
Unpacking libapr1t64:amd64 (1.7.2-3.1build2) ...
Selecting previously unselected package libaprutil1t64:amd64.
Preparing to unpack .../01-libaprutil1t64_1.6.3-1.1ubuntu7_amd64.deb ...
Unpacking libaprutil1t64:amd64 (1.6.3-1.1ubuntu7) ...
Selecting previously unselected package libaprutil1-dbd-sqlite3:amd64.
Preparing to unpack
.../02-libaprutil1-dbd-sqlite3_1.6.3-1.1ubuntu7_amd64.deb ...
Unpacking libaprutil1-dbd-sqlite3:amd64 (1.6.3-1.1ubuntu7) ...
Selecting previously unselected package libaprutil1-ldap:amd64.
Preparing to unpack .../03-libaprutil1-ldap_1.6.3-1.1ubuntu7_amd64.deb ...
Unpacking libaprutil1-ldap:amd64 (1.6.3-1.1ubuntu7) ...
Selecting previously unselected package libjansson4:amd64.
Preparing to unpack .../04-libjansson4_2.14-2build2_amd64.deb ...
Unpacking libjansson4:amd64 (2.14-2build2) ...
Selecting previously unselected package liblua5.4-0:amd64.
Preparing to unpack .../05-liblua5.4-0_5.4.6-3build2_amd64.deb ...
Unpacking liblua5.4-0:amd64 (5.4.6-3build2) ...
Selecting previously unselected package apache2-bin.
Preparing to unpack .../06-apache2-bin_2.4.58-1ubuntu8.3_amd64.deb ...
Unpacking apache2-bin (2.4.58-1ubuntu8.3) ...
Selecting previously unselected package apache2-data.
Preparing to unpack .../07-apache2-data_2.4.58-1ubuntu8.3_all.deb ...
Unpacking apache2-data (2.4.58-1ubuntu8.3) ...
Selecting previously unselected package apache2-utils.
Preparing to unpack .../08-apache2-utils_2.4.58-1ubuntu8.3_amd64.deb ...
Unpacking apache2-utils (2.4.58-1ubuntu8.3) ...
Selecting previously unselected package apache2.
Preparing to unpack .../09-apache2_2.4.58-1ubuntu8.3_amd64.deb ...
Unpacking apache2 (2.4.58-1ubuntu8.3) ...
Selecting previously unselected package libapache2-mod-wsgi-py3.
Preparing to unpack .../10-libapache2-mod-wsgi-py3_5.0.0-1build2_amd64.deb
...
Unpacking libapache2-mod-wsgi-py3 (5.0.0-1build2) ...
Selecting previously unselected package ssl-cert.
Preparing to unpack .../11-ssl-cert_1.1.2ubuntu1_all.deb ...
Unpacking ssl-cert (1.1.2ubuntu1) ...
Setting up libjansson4:amd64 (2.14-2build2) ...
Setting up ssl-cert (1.1.2ubuntu1) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based
frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm
line 79.)
debconf: falling back to frontend: Readline
Created symlink
/etc/systemd/system/multi-user.target.wants/ssl-cert.service →
/usr/lib/systemd/system/ssl-cert.service.
Setting up libapr1t64:amd64 (1.7.2-3.1build2) ...
Setting up liblua5.4-0:amd64 (5.4.6-3build2) ...
Setting up apache2-data (2.4.58-1ubuntu8.3) ...
Setting up libaprutil1t64:amd64 (1.6.3-1.1ubuntu7) ...
Setting up libaprutil1-ldap:amd64 (1.6.3-1.1ubuntu7) ...
Setting up libaprutil1-dbd-sqlite3:amd64 (1.6.3-1.1ubuntu7) ...
Setting up apache2-utils (2.4.58-1ubuntu8.3) ...
Setting up apache2-bin (2.4.58-1ubuntu8.3) ...
Setting up apache2 (2.4.58-1ubuntu8.3) ...
Enabling module mpm_event.
Enabling module authz_core.
Enabling module authz_host.
Enabling module authn_core.
Enabling module auth_basic.
Enabling module access_compat.
Enabling module authn_file.
Enabling module authz_user.
Enabling module alias.
Enabling module dir.
Enabling module autoindex.
Enabling module env.
Enabling module mime.
Enabling module negotiation.
Enabling module setenvif.
Enabling module filter.
Enabling module deflate.
Enabling module status.
Enabling module reqtimeout.
Enabling conf charset.
Enabling conf localized-error-pages.
Enabling conf other-vhosts-access-log.
Enabling conf security.
Enabling conf serve-cgi-bin.
Enabling site 000-default.
Created symlink /etc/systemd/system/multi-user.target.wants/apache2.service
→ /usr/lib/systemd/system/apache2.service.
Created symlink
/etc/systemd/system/multi-user.target.wants/apache-htcacheclean.service →
/usr/lib/systemd/system/apache-htcacheclean.service.
Setting up libapache2-mod-wsgi-py3 (5.0.0-1build2) ...
apache2_invoke: Enable module wsgi
Processing triggers for libc-bin (2.39-0ubuntu8.2) ...
Scanning processes...
Scanning candidates...
Scanning linux images...

Running kernel seems to be up-to-date.

Restarting services...

Service restarts being deferred:
 /etc/needrestart/restart.d/dbus.service
 systemctl restart systemd-logind.service

No containers need to be restarted.

User sessions running outdated binaries:
 minecraftuser @ session #1: login[1049]
 minecraftuser @ user manager service: systemd[1097]

No VM guests are running outdated hypervisor (qemu) binaries on this host.
Virtual host configuration file created at
/etc/apache2/sites-available/mcsli-webui.conf
Listen 5000
'Listen 5000' added to /etc/apache2/ports.conf
sudo: ufw: command not found














sudo: ufw: command not found
***@***.***:~$ sudo systemctl start minecraft.service
***@***.***:~$ cd /
***@***.***:/$ dir
bin                cdrom  home               lib64       mnt   root
 sbin.usr-is-merged  swap.img  usr
bin.usr-is-merged  dev    lib                lost+found  opt   run   snap
             sys       var
boot               etc    lib.usr-is-merged  media       proc  sbin  srv
              tmp
***@***.***:/$ cd opt
***@***.***:/opt$ dir
minecraft
***@***.***:/opt$ cd minecraft
***@***.***:/opt/minecraft$ dir
minecraft_server.1.21.0.jar  server_info.txt
***@***.***:/opt/minecraft$






Thanks,
Richard Meade, Jr.

**Comment by rmeadejr** [comment]
The script is looking for "vanilla-minecraft.X.X.X.jar" but it is saving it
as minecraft.X.X.X.jar


Thanks,
Richard Meade, Jr.
240-676-0164

**Comment by realSZ27** [comment]
I think I see the issue. Minecraft doesn't put the .0 at the end of new versions, so it would just be "1.21". Seems counter-intuitive, but that's how it is. 

I also see a couple of other issues with the script now too.

**Comment by keepittechie** [comment]
This issue has been resolved with merge attached. I redesigned the whole script over the last couple 3 weeks. Thanks for reporting @rmeadejr 
Thank you for all your help as well @realSZ27
