### ISSUE TITLE
Unnecessary jq and curl install

### ISSUE THREAD

**Issue by realSZ27** [keepittechie/mcsli#8]
A tiny, *tiny*, issue. If it even counts as one. But when installing the purpur .jar, you don't need to install jq or curl. All it does is [construct the download url with the server version](https://github.com/keepittechie/mcsli/blob/301889a65d7fb48646cd16ad41b22fd8a4966789/install.sh#L174) and download it with wget.

wget technically isn't needed either because you can do the same thing with curl if you want to change that. It would just cut down one extra package on systems that don't already have both installed.

**Comment by keepittechie** [comment]
Thanks for catching that! You can fix it if you like @realSZ27 I must have missed that.

**Comment by keepittechie** [comment]
I believe I made this correction. Please test on your end and I'll pull the change.

This is my log after installing purpur 1.20.4
josh@ubs24:~/mcsli$ cat /var/log/minecraft_install.log 
openjdk-17-jre-headless
wget
ufw
